name: Deploy to Local Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 

      - name: Install project dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Local Machine
        run: |
          LOCAL_DEPLOY_DIR="/home/wot-raj/Raj/devops-test-demo/my-app"
          cp -r build/* $LOCAL_DEPLOY_DIR
          # cd $LOCAL_DEPLOY_DIR
          # npm install
          # npm start

        working-directory: /home/wot-raj/Raj/devops-test-demo/my-app
