name: Deploy to Local Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and tag Docker image
        run: |
          docker build -t devops-test-demo .
          docker tag devops-test-demo devops-test-demo:latest
        working-directory: /home/wot-raj/Raj/devops-test-demo

      - name: Deploy Docker image to Local Machine
        run: |
          # Start the Docker container on your local machine
          docker run -d -p 3005:3005 devops-test-demo
        working-directory: /home/wot-raj/Raj/devops-test-demo

      - name: Confirm Deployment
        run: |
          # Optionally, you can add a step to check if the application is running
          curl http://localhost:3005
        continue-on-error: true
